# you can skip workflows runs wih some comments in the commits https://docs.github.com/en/actions/how-tos/manage-workflow-runs/skip-workflow-runs

name: Deploy project
on:
    push:
        branches:
            - main

        # paths:
        #   - "src/**"
    workflow_dispatch:
env:
    ENV: production
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install dependencies
              run: npm ci
            - name: run tests
              run: npm test
    build:
        runs-on: ubuntu-latest
        needs: test
        outputs:
            js-file-name: ${{ steps.publish_js_file_name.outputs.js_file_name }}
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run build

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-files

            - name: List files
              run: ls
            - name: deploy
              run: echo "Deploying to production..."
