# you can skip workflows runs wih some comments in the commits https://docs.github.com/en/actions/how-tos/manage-workflow-runs/skip-workflow-runs

name: Deploy project
on:
  push:
    branches:
      - main
      - feature-* #  "*" any word or character other than a slash
      - bugfix/** #  "**" any word  or character and slash
    # paths:
    #   - "src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List files
        run: ls
      - name: deploy
        run: echo "Deploying to production..."
