name: Deploy project
on:
  push:
    branches:
      - main
      - feature-* #  "*" any word or character other than a slash
      - bugfix/** #  "**" any word  or character and slash
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: echo "Deploying to production..."
